variable "prefix" {
  type = string
  validation {
    condition = (
      length(var.prefix) <= 6
    )
    error_message = "Max length is 6 chars."
  }
}

variable "env" {
  type        = string
  description = "Environment"
}

variable "env_short" {
  type = string
  validation {
    condition = (
      length(var.env_short) <= 1
    )
    error_message = "Max length is 1 chars."
  }
}

variable "location" {
  type = string
}

variable "location_short" {
  type        = string
  description = "Location short like eg: neu, weu.."
}

variable "tags" {
  type = map(any)
  default = {
    CreatedBy = "Terraform"
  }
}

variable "domain" {
  type = string
  validation {
    condition = (
      length(var.domain) <= 12
    )
    error_message = "Max length is 12 chars."
  }
}

variable "location_westeurope" {
  type    = string
  default = "westeurope"
}

variable "location_short_westeurope" {
  type        = string
  description = "Location short like eg: weu.."
  default     = "weu"
}

#
# Grafana
#
variable "grafana_zone_redundancy_enabled" {
  type        = bool
  description = "(Required) Whether to enable the zone redundancy setting of the Grafana instance. Changing this forces a new Dashboard Grafana to be created."
}

variable "grafana_major_version" {
  type        = number
  description = "(Required) Which major version of Grafana to deploy. Possible values are 9, 10. Changing this forces a new resource to be created."
}

## Analytics Workspace
variable "law_sku" {
  type        = string
  description = "Sku of the Log Analytics Workspace"
  default     = "PerGB2018"
}

variable "law_retention_in_days" {
  type        = number
  description = "The workspace data retention in days"
  default     = 30
}

variable "law_daily_quota_gb" {
  type        = number
  description = "The workspace daily quota for ingestion in GB."
  default     = -1
}

## Synthetic Monitoring

variable "synthetic_use_private_endpoint" {
  type        = bool
  description = "(Required) if true enables the usage of private endpoint"
}

variable "synthetic_storage_account_replication_type" {
  type        = string
  description = "(Required) table storage replication type"
}

variable "synthetic_self_alert_enabled" {
  type        = bool
  description = "(Optional) enables the alert on the function itself"
  default     = true
}

variable "synthetic_alerts_enabled" {
  type        = bool
  default     = false
  description = "(Optional) Enables alerts generated by the synthetic monitoring probe"
}

## DNS

variable "external_domain" {
  type        = string
  description = "Domain for delegation"
}

variable "dns_zone_prefix" {
  type        = string
  description = "The dns subdomain with env"
}
